name: r-check

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_KEEP_PKG_SOURCE: yes

jobs:
  check:
    name: r-check-${{ matrix.config.os }}-${{ matrix.config.r }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: '4.5'}
          - {os: windows-latest, r: '4.5'}
          - {os: ubuntu-latest,  r: '4.5'}
          - {os: ubuntu-latest,  r: '4.4'}
          - {os: ubuntu-latest,  r: '4.3'}
    steps:
      - name: check-out-repository
        uses: actions/checkout@v5
      - name: install-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          extra-repositories: https://r-multiverse.r-universe.dev
      - name: install-r-dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: r
          extra-packages: any::rcmdcheck
      - name: check-r-package
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: r